### ISSUE TITLE
Test accuracy

### ISSUE THREAD

**Issue by purva98** [NeerajPise/deepfake-detection-image#1]
Hi Neeraj, what test accuracy did u get?
Can you tell me, how well does it perform on unseen test images from other dataset?

**Comment by NeerajPise** [comment]
The purpose of this repository was to edit the code to accept images instead of videos (as in the original repository here https://github.com/xinyooo/deepfake-detection). Sadly, the original repository doesn't work well with any dataset that I tried (Kaggle deepfake/ FaceForensics++). It is severely overfitting. Hence, this repo replicates the behaviour. You could still try it and notify me if you get any good results with this or other methods. 
Thanks!
